name: keryilmaz
favicon: null
layout_spectrum: 0.27415200183168054
typography_spectrum: 0.39731334312818944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040001'
    - '#d1e6e7'
    - '#008eac'
    - '#6d8877'
    - '#68202d'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
