name: keryilmaz
favicon: null
layout_spectrum: 0.27415200183168054
typography_spectrum: 0.39731334312818944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09191535972058773
  lightness: 0.46684282133355737
  saturation: 0.641391390003264
  rhythmicContrast: 0.2119751051068306
purpose: []
